[2024-04-19 20:19:42,018] INFO _log() L224   * Restarting with stat - call_trace=C:\Users\Saulo Canto\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L224 
[2024-04-19 20:19:43,464] INFO _log() L224  192.168.0.40 - - [19/Apr/2024 20:19:43] "[35m[1mGET /atividades_all HTTP/1.1[0m" 500 - - call_trace=C:\Users\Saulo Canto\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L224 
[2024-04-19 20:19:43,474] ERROR _log() L224  Error on request:
Traceback (most recent call last):
  File "C:\Users\Saulo Canto\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\serving.py", line 335, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Saulo Canto\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\serving.py", line 322, in execute
    application_iter = app(environ, start_response)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Saulo Canto\new_test_path\desenvolvimento-full-stack\desenvolvimento-full-stack-basico\aula-3\meu_app_api\app.py", line 9, in <module>
    from schemas import *
  File "C:\Users\Saulo Canto\new_test_path\desenvolvimento-full-stack\desenvolvimento-full-stack-basico\aula-3\meu_app_api\schemas\__init__.py", line 2, in <module>
    from schemas.atividades import AtividadesSchema, AtividadesBuscaSchema, AtividadesViewSchema, \
  File "C:\Users\Saulo Canto\new_test_path\desenvolvimento-full-stack\desenvolvimento-full-stack-basico\aula-3\meu_app_api\schemas\atividades.py", line 19
    colaborador: str atividades.filter_by(colaborador=colaborador)
                     ^^^^^^^^^^
SyntaxError: invalid syntax - call_trace=C:\Users\Saulo Canto\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L224 
[2024-04-19 20:19:44,003] INFO _log() L224  192.168.0.40 - - [19/Apr/2024 20:19:44] "[35m[1mGET /atividades_all HTTP/1.1[0m" 500 - - call_trace=C:\Users\Saulo Canto\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L224 
[2024-04-19 20:19:44,005] ERROR _log() L224  Error on request:
Traceback (most recent call last):
  File "C:\Users\Saulo Canto\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\serving.py", line 335, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Saulo Canto\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\serving.py", line 322, in execute
    application_iter = app(environ, start_response)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Saulo Canto\new_test_path\desenvolvimento-full-stack\desenvolvimento-full-stack-basico\aula-3\meu_app_api\app.py", line 9, in <module>
    from schemas import *
  File "C:\Users\Saulo Canto\new_test_path\desenvolvimento-full-stack\desenvolvimento-full-stack-basico\aula-3\meu_app_api\schemas\__init__.py", line 2, in <module>
    from schemas.atividades import AtividadesSchema, AtividadesBuscaSchema, AtividadesViewSchema, \
  File "C:\Users\Saulo Canto\new_test_path\desenvolvimento-full-stack\desenvolvimento-full-stack-basico\aula-3\meu_app_api\schemas\atividades.py", line 19
    colaborador: str atividades.filter_by(colaborador=colaborador)
                     ^^^^^^^^^^
SyntaxError: invalid syntax - call_trace=C:\Users\Saulo Canto\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L224 
[2024-04-19 20:19:44,522] INFO _log() L224  192.168.0.40 - - [19/Apr/2024 20:19:44] "[35m[1mGET /atividades_all HTTP/1.1[0m" 500 - - call_trace=C:\Users\Saulo Canto\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L224 
[2024-04-19 20:19:44,523] ERROR _log() L224  Error on request:
Traceback (most recent call last):
  File "C:\Users\Saulo Canto\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\serving.py", line 335, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Saulo Canto\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\serving.py", line 322, in execute
    application_iter = app(environ, start_response)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Saulo Canto\new_test_path\desenvolvimento-full-stack\desenvolvimento-full-stack-basico\aula-3\meu_app_api\app.py", line 9, in <module>
    from schemas import *
  File "C:\Users\Saulo Canto\new_test_path\desenvolvimento-full-stack\desenvolvimento-full-stack-basico\aula-3\meu_app_api\schemas\__init__.py", line 2, in <module>
    from schemas.atividades import AtividadesSchema, AtividadesBuscaSchema, AtividadesViewSchema, \
  File "C:\Users\Saulo Canto\new_test_path\desenvolvimento-full-stack\desenvolvimento-full-stack-basico\aula-3\meu_app_api\schemas\atividades.py", line 19
    colaborador: str atividades.filter_by(colaborador=colaborador)
                     ^^^^^^^^^^
SyntaxError: invalid syntax - call_trace=C:\Users\Saulo Canto\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L224 
[2024-04-19 20:19:44,874] INFO _log() L224  192.168.0.40 - - [19/Apr/2024 20:19:44] "[35m[1mGET /atividades_all HTTP/1.1[0m" 500 - - call_trace=C:\Users\Saulo Canto\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L224 
[2024-04-19 20:19:44,876] ERROR _log() L224  Error on request:
Traceback (most recent call last):
  File "C:\Users\Saulo Canto\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\serving.py", line 335, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Saulo Canto\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\serving.py", line 322, in execute
    application_iter = app(environ, start_response)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Saulo Canto\new_test_path\desenvolvimento-full-stack\desenvolvimento-full-stack-basico\aula-3\meu_app_api\app.py", line 9, in <module>
    from schemas import *
  File "C:\Users\Saulo Canto\new_test_path\desenvolvimento-full-stack\desenvolvimento-full-stack-basico\aula-3\meu_app_api\schemas\__init__.py", line 2, in <module>
    from schemas.atividades import AtividadesSchema, AtividadesBuscaSchema, AtividadesViewSchema, \
  File "C:\Users\Saulo Canto\new_test_path\desenvolvimento-full-stack\desenvolvimento-full-stack-basico\aula-3\meu_app_api\schemas\atividades.py", line 19
    colaborador: str atividades.filter_by(colaborador=colaborador)
                     ^^^^^^^^^^
SyntaxError: invalid syntax - call_trace=C:\Users\Saulo Canto\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L224 
[2024-04-19 20:19:49,275] INFO _log() L224  192.168.0.40 - - [19/Apr/2024 20:19:49] "[35m[1mGET /atividades_all HTTP/1.1[0m" 500 - - call_trace=C:\Users\Saulo Canto\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L224 
[2024-04-19 20:19:49,277] ERROR _log() L224  Error on request:
Traceback (most recent call last):
  File "C:\Users\Saulo Canto\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\serving.py", line 335, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Saulo Canto\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\serving.py", line 322, in execute
    application_iter = app(environ, start_response)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Saulo Canto\new_test_path\desenvolvimento-full-stack\desenvolvimento-full-stack-basico\aula-3\meu_app_api\app.py", line 9, in <module>
    from schemas import *
  File "C:\Users\Saulo Canto\new_test_path\desenvolvimento-full-stack\desenvolvimento-full-stack-basico\aula-3\meu_app_api\schemas\__init__.py", line 2, in <module>
    from schemas.atividades import AtividadesSchema, AtividadesBuscaSchema, AtividadesViewSchema, \
  File "C:\Users\Saulo Canto\new_test_path\desenvolvimento-full-stack\desenvolvimento-full-stack-basico\aula-3\meu_app_api\schemas\atividades.py", line 19
    colaborador: str atividades.filter_by(colaborador=colaborador)
                     ^^^^^^^^^^
SyntaxError: invalid syntax - call_trace=C:\Users\Saulo Canto\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L224 
[2024-04-19 20:19:49,402] INFO _log() L224   * Detected change in 'C:\\Users\\Saulo Canto\\new_test_path\\desenvolvimento-full-stack\\desenvolvimento-full-stack-basico\\aula-3\\meu_app_api\\schemas\\atividades.py', reloading - call_trace=C:\Users\Saulo Canto\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L224 
[2024-04-19 20:19:49,616] INFO _log() L224   * Restarting with stat - call_trace=C:\Users\Saulo Canto\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L224 
[2024-04-19 20:19:50,785] INFO _log() L224  192.168.0.40 - - [19/Apr/2024 20:19:50] "[35m[1mGET /atividades_all HTTP/1.1[0m" 500 - - call_trace=C:\Users\Saulo Canto\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L224 
[2024-04-19 20:19:50,789] INFO _log() L224  192.168.0.40 - - [19/Apr/2024 20:19:50] "[35m[1mGET /atividades_all HTTP/1.1[0m" 500 - - call_trace=C:\Users\Saulo Canto\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L224 
[2024-04-19 20:19:53,152] INFO _log() L224   * Detected change in 'C:\\Users\\Saulo Canto\\new_test_path\\desenvolvimento-full-stack\\desenvolvimento-full-stack-basico\\aula-3\\meu_app_api\\schemas\\atividades.py', reloading - call_trace=C:\Users\Saulo Canto\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L224 
[2024-04-19 20:19:53,270] INFO _log() L224   * Restarting with stat - call_trace=C:\Users\Saulo Canto\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L224 
[2024-04-19 20:19:55,854] INFO _log() L224   * Restarting with stat - call_trace=C:\Users\Saulo Canto\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L224 
